export const DEFAULT_MESSAGE = {
  id: '-1',
  type: 'Message',
  // conversationid: '19:4e76a079f3564b1fbfce0a5e0d2d4a92@thread.v2',
  // conversationLink: 'blah/19:4e76a079f3564b1fbfce0a5e0d2d4a92@thread.v2',
  // from: '8:orgid:b8c63ba2-5dd6-42d2-9ee4-c729ac382f7b',
  messagetype: 'RichText/Html',
  contenttype: 'Text',
  // imdisplayname: 'Muhammad Waqar',
  // callId: '',
  // state: 0,
  // version: '0',
  // amsreferences: [],
  // properties: {
  //   importance: '',
  //   subject: '',
  //   title: '',
  //   cards: '[]',
  //   links: '[]',
  //   mentions: '[]',
  //   onbehalfof: null,
  //   files: '[]',
  //   policyViolation: null,
  //   formatVariant: 'TEAMS',
  // },
  // crossPostChannels: [],
};
// export const DEFAULT_MESSAGE = {
//   id: '-1',
//   type: 'Message',
//   conversationid: '48:notes',
//   conversationLink: 'blah/48:notes',
//   from: '8:orgid:b8c63ba2-5dd6-42d2-9ee4-c729ac382f7b',
//   messagetype: 'RichText/Html',
//   contenttype: 'Text',
//   imdisplayname: 'Muhammad Waqar',
//   callId: '',
//   state: 0,
//   version: '0',
//   amsreferences: [],
//   properties: {
//     importance: '',
//     subject: '',
//     title: '',
//     cards: '[]',
//     links: '[]',
//     mentions: '[]',
//     onbehalfof: null,
//     files: '[]',
//     policyViolation: null,
//     formatVariant: 'TEAMS',
//   },
//   crossPostChannels: [],
// };
