export const teams_payload = {
  id: '-1',
  type: 'Message',
  conversationid: '19:aad56efec79244d5b50bf779c9198fbb@thread.v2',
  conversationLink: 'blah/19:aad56efec79244d5b50bf779c9198fbb@thread.v2',
  from: '8:orgid:b8c63ba2-5dd6-42d2-9ee4-c729ac382f7b',
  messagetype: 'RichText/Html',
  contenttype: 'Text',
  imdisplayname: 'Muhammad Waqar',
  callId: '',
  state: 0,
  version: '0',
  amsreferences: [],
  properties: {
    importance: '',
    subject: '',
    title: '',
    cards: '[]',
    links: '[]',
    mentions: '[]',
    onbehalfof: null,
    files: '[]',
    policyViolation: null,
    formatVariant: 'TEAMS',
  },
  crossPostChannels: [],
}

export const test_teams = {
  id: '-1',
  type: 'Message',
  conversationid: '48:notes',
  conversationLink: 'blah/48:notes',
  from: '8:orgid:b8c63ba2-5dd6-42d2-9ee4-c729ac382f7b',
  composetime: '2025-06-02T18:32:45.613Z',
  originalarrivaltime: '2025-06-02T18:32:45.613Z',
  content: '<p>hi</p>',
  messagetype: 'RichText/Html',
  contenttype: 'Text',
  imdisplayname: 'Muhammad Waqar',
  clientmessageid: '4033248974173312551',
  callId: '',
  state: 0,
  version: '0',
  amsreferences: [],
  properties: {
    importance: '',
    subject: '',
    title: '',
    cards: '[]',
    links: '[]',
    mentions: '[]',
    onbehalfof: null,
    files: '[]',
    policyViolation: null,
    formatVariant: 'TEAMS',
  },
  crossPostChannels: [],
}
